version: '3.9'


networks:
  app-tier:
    driver: bridge


volumes:
  HR_HMS_DATA:


services:

  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - HRMS:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: HRMS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-tier


  backend:
    build: .
    container_name: backend_service
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8182:8182'
    command: /bin/bash -c "npm run build && npm start"
    networks:
      - app-tier
